-- Generated from generator/demo_specs/aws-malaysia-islamic-finance-sukuk.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-malaysia-islamic-finance-sukuk
-- This is the schema that is actually deployed for MY_ISLAMIC_FINANCE_SUKUK.

-- Alerts fire on the bottom tail of Avg Yield
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_AVG_YIELD) AS T
  FROM RAW.MARKET_DATA
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_AVG_YIELD <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_AVG_YIELD), 2) AS AVG_YIELD,
  ROUND(AVG(f.KPI_FOREIGN_HOLDINGS), 2) AS AVG_FOREIGN_HOLDINGS,
  ROUND(AVG(f.KPI_AVG_TENOR), 2) AS AVG_TENOR,
  ROUND(AVG(f.KPI_SPREAD_VS_MGS), 2) AS AVG_SPREAD_VS_MGS
FROM RAW.MARKET_DATA f
JOIN RAW.PORTFOLIO_DOCS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_AVG_YIELD), 2) AS AVG_YIELD,
  ROUND(AVG(f.KPI_FOREIGN_HOLDINGS), 2) AS AVG_FOREIGN_HOLDINGS,
  ROUND(AVG(f.KPI_AVG_TENOR), 2) AS AVG_TENOR,
  ROUND(AVG(f.KPI_SPREAD_VS_MGS), 2) AS AVG_SPREAD_VS_MGS
FROM RAW.MARKET_DATA f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_AVG_YIELD) AS KPI_AVG_YIELD, AVG(KPI_FOREIGN_HOLDINGS) AS KPI_FOREIGN_HOLDINGS, AVG(KPI_AVG_TENOR) AS KPI_AVG_TENOR, AVG(KPI_SPREAD_VS_MGS) AS KPI_SPREAD_VS_MGS FROM RAW.MARKET_DATA),
     en AS (SELECT SUM(KPI_OUTSTANDING_SUKUK) AS KPI_OUTSTANDING_SUKUK, SUM(KPI_NEW_ISSUANCE_YTD) AS KPI_NEW_ISSUANCE_YTD, SUM(KPI_ACTIVE_ISSUERS) AS KPI_ACTIVE_ISSUERS FROM RAW.PORTFOLIO_DOCS)
  SELECT 1 AS SORT_ORDER, 'Outstanding Sukuk' AS TITLE, KPI_OUTSTANDING_SUKUK AS VALUE_NUM, 'RM' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_OUTSTANDING_SUKUK) / 1000000000000), 1) AS DECIMAL(38,1))) || 'T' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'New Issuance (YTD)' AS TITLE, KPI_NEW_ISSUANCE_YTD AS VALUE_NUM, 'RM' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_NEW_ISSUANCE_YTD) / 1000000000)) AS DECIMAL(38,0))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Avg Yield' AS TITLE, KPI_AVG_YIELD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_YIELD), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active Issuers' AS TITLE, KPI_ACTIVE_ISSUERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_ISSUERS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Foreign Holdings' AS TITLE, KPI_FOREIGN_HOLDINGS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FOREIGN_HOLDINGS)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Avg Tenor' AS TITLE, KPI_AVG_TENOR AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_TENOR), 1) AS DECIMAL(38,1))) || ' ' || 'yrs' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Spread vs MGS' AS TITLE, KPI_SPREAD_VS_MGS AS VALUE_NUM, '+' || TO_VARCHAR(CAST(ROUND((KPI_SPREAD_VS_MGS)) AS DECIMAL(38,0))) || ' ' || 'bps' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
