-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT holding.ID AS ENTITY_ID, holding.NAME AS ENTITY_NAME,
       holding.CUSTODIAN, holding.CATEGORY, holding.RISK_TIER, holding.STATUS,
       COUNT(*) AS EVENT_COUNT,
       SUM(observation.SETTLEMENT_COUNT) AS SETTLEMENT_COUNT,
       SUM(observation.VALUE_MYR) AS VALUE_MYR,
       SUM(observation.BREAK_COUNT) AS BREAK_COUNT,
       SUM(observation.ESCALATED_COUNT) AS ESCALATED_COUNT,
       SUM(observation.SLA_BREACHED) AS SLA_BREACH_COUNT,
       SUM(observation.RECON_DUE) AS RECON_DUE,
       SUM(observation.RECON_COMPLETED) AS RECON_COMPLETED,
       100.0 * (SUM(observation.SETTLEMENT_COUNT) - SUM(observation.BREAK_COUNT)) / NULLIF(SUM(observation.SETTLEMENT_COUNT), 0) AS MATCH_RATE_PCT,
       100.0 * SUM(observation.ESCALATED_COUNT) / NULLIF(SUM(observation.BREAK_COUNT), 0) AS ESCALATION_SHARE_PCT,
       100.0 * SUM(observation.RECON_COMPLETED) / NULLIF(SUM(observation.RECON_DUE), 0) AS RECON_COMPLIANCE_PCT,
       AVG(observation.AUTOMATCH_FAIL_PCT) AS AVG_AUTOMATCH_FAIL_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.HOLDING_DAILY observation
JOIN RAW.HOLDINGS holding ON holding.ID = observation.ENTITY_ID
GROUP BY holding.ID, holding.NAME, holding.CUSTODIAN, holding.CATEGORY, holding.RISK_TIER, holding.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(SETTLEMENT_COUNT) AS SETTLEMENT_COUNT, SUM(VALUE_MYR) AS VALUE_MYR,
       SUM(BREAK_COUNT) AS BREAK_COUNT, SUM(ESCALATED_COUNT) AS ESCALATED_COUNT,
       100.0 * SUM(ESCALATED_COUNT) / NULLIF(SUM(BREAK_COUNT), 0) AS ESCALATION_SHARE_PCT
FROM RAW.HOLDING_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.BREAK_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT BREAK_REASON, SUM(BREAK_COUNT) AS BREAK_COUNT,
       SUM(ESCALATED_COUNT) AS ESCALATED_COUNT,
       SUM(SLA_BREACHED) AS SLA_BREACH_COUNT,
       SUM(VALUE_MYR) AS EXPOSED_VALUE_MYR,
       100.0 * SUM(ESCALATED_COUNT) / NULLIF(SUM(BREAK_COUNT), 0) AS ESCALATION_SHARE_PCT
FROM RAW.HOLDING_DAILY
WHERE BREAK_COUNT > 0
GROUP BY BREAK_REASON;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(SETTLEMENT_COUNT) AS SETTLEMENTS, SUM(BREAK_COUNT) AS BREAKS,
         SUM(ESCALATED_COUNT) AS ESCALATED, SUM(SLA_BREACHED) AS BREACHES, SUM(VALUE_MYR) AS VALUE_MYR,
         SUM(RECON_DUE) AS RECON_DUE, SUM(RECON_COMPLETED) AS RECON_COMPLETED,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.HOLDING_DAILY
), book AS (SELECT COUNT(*) AS HOLDING_COUNT FROM RAW.HOLDINGS),
documents AS (
  SELECT 100.0 * SUM(LEAST(ON_FILE_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT,
         SUM(PENDING_QTY) AS PENDING
  FROM RAW.HOLDING_DOCUMENTS
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'Settlement Match Rate' AS TITLE,
         100.0 * (SETTLEMENTS - BREAKS) / NULLIF(SETTLEMENTS, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Settlement Breaks', BREAKS, '' FROM observations
  UNION ALL SELECT 3, 'Escalated to Custodian Investigation', ESCALATED, '' FROM observations
  UNION ALL SELECT 4, 'Escalation Rate', 100.0 * ESCALATED / NULLIF(BREAKS, 0), '%' FROM observations
  UNION ALL SELECT 5, 'Resolution SLA Breaches', BREACHES, '' FROM observations
  UNION ALL SELECT 6, 'Settled Value (MYR B)', VALUE_MYR / 1e9, '' FROM observations
  UNION ALL SELECT 7, 'Instructions Processed', SETTLEMENTS, '' FROM observations
  UNION ALL SELECT 8, 'Position Reconciliation Compliance', 100.0 * RECON_COMPLETED / NULLIF(RECON_DUE, 0), '%' FROM observations
  UNION ALL SELECT 9, 'Holdings Monitored', HOLDING_COUNT, '' FROM book
  UNION ALL SELECT 10, 'Holding File Coverage', COVERAGE_PCT, '%' FROM documents
  UNION ALL SELECT 11, 'Holding Documents Pending', PENDING, '' FROM documents
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                WHEN metrics.SORT_ORDER = 1 THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 2), '990.00'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.BREAK_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
