-- Break escalation risk scoring and break-volume forecast over the synthetic snapshot.
-- Predicts P(a settlement break on the holding is escalated to custodian investigation in the next 7 days)
-- per holding and reports out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.ESCALATION_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, a.CATEGORY, a.RISK_TIER, a.YEARS_HELD,
       r.AUTOMATCH_FAIL_PCT, r.AVG_BREAK_AGE_HOURS,
       AVG(r.AUTOMATCH_FAIL_PCT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS AUTOMATCH_FAIL_7D,
       SUM(r.ESCALATED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS ESCALATED_30D,
       IFF(SUM(r.ESCALATED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'ESCALATED', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.HOLDING_DAILY r JOIN RAW.HOLDINGS a ON a.ID = r.ENTITY_ID
-- Custodian-wide system outages are not holding-driven, so they are excluded from training.
WHERE r.BREAK_REASON <> 'Custodian system outage';

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.ESCALATION_TRAIN AS
SELECT CATEGORY, RISK_TIER, YEARS_HELD, AUTOMATCH_FAIL_PCT, AVG_BREAK_AGE_HOURS, AUTOMATCH_FAIL_7D, ESCALATED_30D, LABEL
FROM ML.ESCALATION_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.ESCALATION_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, RISK_TIER, YEARS_HELD, AUTOMATCH_FAIL_PCT, AVG_BREAK_AGE_HOURS, AUTOMATCH_FAIL_7D, ESCALATED_30D, LABEL
FROM ML.ESCALATION_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.ESCALATION_RISK_MODEL(
  INPUT_DATA => TABLE(ML.ESCALATION_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.ESCALATION_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.ESCALATION_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'RISK_TIER', RISK_TIER, 'YEARS_HELD', YEARS_HELD,
           'AUTOMATCH_FAIL_PCT', AUTOMATCH_FAIL_PCT, 'AVG_BREAK_AGE_HOURS', AVG_BREAK_AGE_HOURS,
           'AUTOMATCH_FAIL_7D', AUTOMATCH_FAIL_7D, 'ESCALATED_30D', ESCALATED_30D)):probability:ESCALATED::FLOAT AS P
  FROM ML.ESCALATION_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'ESCALATED', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'ESCALATED', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'ESCALATED', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'ESCALATED', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per holding (label unknown, so excluded from features).
CREATE TABLE ML.ESCALATION_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.ESCALATION_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.ESCALATION_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'RISK_TIER', RISK_TIER, 'YEARS_HELD', YEARS_HELD,
           'AUTOMATCH_FAIL_PCT', AUTOMATCH_FAIL_PCT, 'AVG_BREAK_AGE_HOURS', AVG_BREAK_AGE_HOURS,
           'AUTOMATCH_FAIL_7D', AUTOMATCH_FAIL_7D, 'ESCALATED_30D', ESCALATED_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:ESCALATED::FLOAT, 4) AS ESCALATION_PROB_7D,
       CASE WHEN P:probability:ESCALATED::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:ESCALATED::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Portfolio-wide break-volume forecast (14 days) from the daily series, for back-office staffing.
CREATE VIEW ML.DAILY_BREAKS AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(BREAK_COUNT)::FLOAT AS BREAK_COUNT
FROM RAW.HOLDING_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.BREAK_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_BREAKS),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'BREAK_COUNT'
);

CREATE TABLE ML.BREAK_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS BREAK_COUNT,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.BREAK_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
