-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Sukuk Portfolio Analytics
-- ============================================================================
USE DATABASE ISLAMIC_SUKUK_PORTFOLIO;
USE SCHEMA ML;

-- ML.FORECAST: YIELD_CURVE_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.YIELD_CURVE_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.YIELD_CURVES'),
  SERIES_COLNAME => 'STRUCTURE_TYPE',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'YIELD_PCT'
  
);

CREATE OR REPLACE TABLE ML.YIELD_CURVE_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.YIELD_CURVE_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

