-- ============================================================================
-- 99_RESET.SQL — Reset Sukuk Portfolio Analytics to clean demo state
-- ============================================================================
USE DATABASE ISLAMIC_SUKUK_PORTFOLIO;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_MARKET_DATA SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REVALUE_PORTFOLIO SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_YIELDS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.PORTFOLIO_SUMMARY REFRESH;
ALTER DYNAMIC TABLE CURATED.YIELD_CURVES REFRESH;
ALTER DYNAMIC TABLE CURATED.COUNTERPARTY_RISK REFRESH;
ALTER DYNAMIC TABLE CURATED.MATURITY_LADDER REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM ISLAMIC_SUKUK_PORTFOLIO.RAW.SUKUK_HOLDINGS → 500
-- SELECT COUNT(*) FROM ISLAMIC_SUKUK_PORTFOLIO.RAW.VALUATIONS → 10000
-- SELECT COUNT(*) FROM ISLAMIC_SUKUK_PORTFOLIO.RAW.MARKET_DATA → 50000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST_YIELDS RESUME;
ALTER TASK IF EXISTS APP.TASK_REVALUE_PORTFOLIO RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_MARKET_DATA RESUME;
